# Generated by Django 3.0.7 on 2020-08-26 21:22

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swarms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name_full', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_tel', models.CharField(max_length=20)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
                ('swarm_street_address1', models.CharField(max_length=80)),
                ('swarm_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('swarm_county', models.CharField(blank=True, max_length=80, null=True)),
                ('swarm_town_or_city', models.CharField(max_length=40)),
                ('swarm_country', django_countries.fields.CountryField(max_length=2)),
                ('swarm_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('swarm_message', models.TextField()),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swarms', to='profiles.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralEnquiries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name_full', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_tel', models.CharField(max_length=20)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
                ('enquiry_message', models.TextField()),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_enqs', to='profiles.UserProfile')),
            ],
        ),
    ]
