# Generated by Django 3.0.7 on 2020-08-26 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralEnquiries',
            new_name='GeneralEnquiry',
        ),
        migrations.RenameModel(
            old_name='Swarms',
            new_name='Swarm',
        ),
    ]
