# Generated by Django 3.0.7 on 2020-09-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200826_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swarm',
            old_name='swarm_town_or_city',
            new_name='swarm_city',
        ),
    ]
