# Generated by Django 3.0.7 on 2020-09-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20200916_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalenquiry',
            old_name='enquiry_message',
            new_name='message_body',
        ),
        migrations.RenameField(
            model_name='swarm',
            old_name='swarm_message',
            new_name='message_body',
        ),
    ]
