# Generated by Django 3.0.7 on 2020-09-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=32)),
                ('status_friendly', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='town_or_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_cost',
            new_name='cost_delivery',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='grand_total',
            new_name='cost_grand_total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_total',
            new_name='cost_total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='name_full',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product',
            new_name='product_line',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.OrderStatus'),
        ),
    ]
