# Generated by Django 3.0.7 on 2020-09-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200910_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creation_method',
            field=models.CharField(editable=False, max_length=16, null=True),
        ),
    ]
