# Generated by Django 3.0.7 on 2020-08-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='sku',
            new_name='skup1',
        ),
        migrations.AddField(
            model_name='productstock',
            name='skup2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
