# Generated by Django 3.0.7 on 2020-09-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200826_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstock',
            old_name='variety_friendly',
            new_name='variety_name',
        ),
    ]
